name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    env:
      ARTIFACT_NAME: "dir-tree-export"

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, 386, arm64, arm]
        exclude:
          - goos: darwin # macOS
            goarch: 386
          - goos: darwin # macOS
            goarch: arm64
          - goos: darwin
            goarch: arm  # macOS non supporta armv7
          - goos: windows
            goarch: arm  # Windows ARM non standard in Go

    steps:

      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Set up Go
        id: setup-go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build Go binary
        id: build
        run: |
          cd src/
          mkdir -p dist
      
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then EXT=".exe"; fi
      
          OUTPUT="$ARTIFACT_NAME-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}"
          
          if [ "${{ matrix.goarch }}" = "arm" ]; then
            OUTPUT="${OUTPUT}v7"
            echo "Building $OUTPUT$EXT with GOARM=7..."
            GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} GOARM=7 go build -o "dist/$OUTPUT$EXT" main.go
          else
            echo "Building $OUTPUT$EXT..."
            GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o "dist/$OUTPUT$EXT" main.go
          fi

      - name: Get last commit message
        id: last_commit
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: dir-tree-export-${{ github.ref_name }}
          body: |
            **Dir Tree Export ${{ github.ref_name }}**
            Scarica l'eseguibile di `${{ env.ARTIFACT_NAME }}` compatibile con il tuo sistema operativo e architettura dalla tabella seguente o dalla sezione Assets.
            | Sistema        | Architettura | File                                                                |
            |----------------|--------------|---------------------------------------------------------------------|
            | Linux          | amd64        | `[${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}-linux-amd64](https://github.com/fvlgnn/dir-tree-export/releases/download/${{ github.ref_name }}/${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}-linux-amd64)` |
            | Linux          | 386          | `[${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}-linux-386](https://github.com/fvlgnn/dir-tree-export/releases/download/${{ github.ref_name }}/${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}-linux-386)` |
            | Linux          | arm (v7) *   | `[${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}-linux-armv7](https://github.com/fvlgnn/dir-tree-export/releases/download/${{ github.ref_name }}/${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}-linux-armv7)` |
            | Linux          | arm64 *      | `[${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}-linux-arm64](https://github.com/fvlgnn/dir-tree-export/releases/download/${{ github.ref_name }}/${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}-linux-arm64)` |
            | Windows        | amd64        | `[${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}-windows-amd64.exe](https://github.com/fvlgnn/dir-tree-export/releases/download/${{ github.ref_name }}/${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}-windows-amd64.exe)` |
            | Windows        | 386          | `[${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}-windows-386.exe](https://github.com/fvlgnn/dir-tree-export/releases/download/${{ github.ref_name }}/${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}-windows-386.exe)` |
            | macOS (Darwin) | amd64        | `[${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}-darwin-amd64](https://github.com/fvlgnn/dir-tree-export/releases/download/${{ github.ref_name }}/${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}-darwin-amd64)` |
            _* Raspberry Pi 2/3 architettura `linux-armv7` | Raspberry Pi 4/5  architettura `linux-arm64`._
            ---
            📝 **Ultimo commit:** `${{ steps.last_commit.outputs.message }}`
          draft: false
          prerelease: false
          files: src/dist/*
